import { injectable } from 'inversify';
import fs from 'fs';
import path from 'path';

@injectable()
export class DistillationService {
  private readonly DISTILL_FILE = '.ai-core/rules/ironclad-distilled.md';

  public async distillPatterns(): Promise<void> {
    const content = `# 🧠 Ironclad Distilled Intelligence
*Auto-generated by the Ironclad Evolution Engine.*

## 1. Output Enforcement (from full-output-enforcement)
- **Mandate**: NEVER use placeholder comments (\`// TODO\`, \`// implement here\`, \`...\`).
- **Action**: Write the full, working implementation every single time.

## 2. Deep Architecture (from mattpocock/skills)
- **Mandate**: Surface architectural friction and propose deepening opportunities.
- **Action**: Prioritize locality and leverage. Use explicit composition over inheritance. Ensure the interface is the test surface.

## 3. Persistent Memory (from claude-mem & agentdb)
- **Mandate**: Maintain cross-session state via memory banks and Vector DBs.
- **Action**: Document architectural decisions in \`ADRs\` and synchronize business context with semantic search engines.

## 4. Swarm Orchestration (from ECC & compound-engineering)
- **Mandate**: Never work alone on complex, multi-file tasks.
- **Action**: Spawn parallel agent swarms: \`feature-dev:code-architect\` (design) -> \`coder\` (draft) -> \`reviewer\` (audit).

## 5. Visual Masterpiece (from ui-ux-pro-max & taste-skill)
- **Mandate**: Reject generic, AI-slop UI patterns.
- **Action**: Enforce premium visual design standards (bento grids, cinematic aesthetic, precise typography, micro-motion).

## 6. Systematic Methodology (from superpowers & Understand-Anything)
- **Mandate**: Methodology is Ironclad. Never skip to implementation.
- **Action**: Always follow the 5-step loop: Understand -> Plan -> Delegate -> Implement -> Verify.
`;

    fs.mkdirSync(path.dirname(this.DISTILL_FILE), { recursive: true });
    fs.writeFileSync(this.DISTILL_FILE, content);
  }

  public async upgradeMandates(): Promise<void> {
    const ruleFiles = ['.clinerules', '.cursorrules', '.windsurfrules', 'CLAUDE.md'];
    ruleFiles.forEach(file => {
      if (fs.existsSync(file)) {
        let fileContent = fs.readFileSync(file, 'utf-8');
        if (!fileContent.includes('ironclad-distilled.md')) {
          fileContent += '\n---\n- **Distilled Intelligence**: Refer to \`.ai-core/rules/ironclad-distilled.md\` for consolidated elite mandates.';
          fs.writeFileSync(file, fileContent);
        }
      }
    });

    if (fs.existsSync('GEMINI.md')) {
      const timestamp = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
      let geminiContent = fs.readFileSync('GEMINI.md', 'utf-8');
      geminiContent = geminiContent.replace(/\*Last Updated:.*\*/, `*Last Updated: ${timestamp} (Phase 5 Evolution: V3 God-Tier Core)*`);
      fs.writeFileSync('GEMINI.md', geminiContent);
    }
  }
}
