import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import shell from 'shelljs';

export async function upgradeAction() {
  const spinner = ora('Triggering Ironclad Evolution Loop...').start();

  // 1. Distill Intelligence
  spinner.text = 'Distilling elite patterns from fetched repositories...';
  const DISTILL_FILE = '.ai-core/rules/ironclad-distilled.md';
  const content = `# 🧠 Ironclad Distilled Intelligence
*Auto-generated by the Ironclad Evolution Engine.*

## 1. Output Enforcement (from full-output-enforcement)
- **Mandate**: NEVER use placeholder comments (\`// TODO\`, \`// implement here\`, \`...\`).
- **Action**: Write the full, working implementation every single time.

## 2. Deep Architecture (from mattpocock/skills)
- **Mandate**: Surface architectural friction and propose deepening opportunities.
- **Action**: Prioritize locality and leverage. Use explicit composition over inheritance. Ensure the interface is the test surface.

## 3. Persistent Memory (from claude-mem & agentdb)
- **Mandate**: Maintain cross-session state via memory banks and Vector DBs.
- **Action**: Document architectural decisions in \`ADRs\` and synchronize business context with semantic search engines.

## 4. Swarm Orchestration (from ECC & compound-engineering)
- **Mandate**: Never work alone on complex, multi-file tasks.
- **Action**: Spawn parallel agent swarms: \`feature-dev:code-architect\` (design) -> \`coder\` (draft) -> \`reviewer\` (audit).

## 5. Visual Masterpiece (from ui-ux-pro-max & taste-skill)
- **Mandate**: Reject generic, AI-slop UI patterns.
- **Action**: Enforce premium visual design standards (bento grids, cinematic aesthetic, precise typography, micro-motion).

## 6. Systematic Methodology (from superpowers & Understand-Anything)
- **Mandate**: Methodology is Ironclad. Never skip to implementation.
- **Action**: Always follow the 5-step loop: Understand -> Plan -> Delegate -> Implement -> Verify.
`;

  try {
    fs.mkdirSync('.ai-core/rules', { recursive: true });
    fs.writeFileSync(DISTILL_FILE, content);
    spinner.succeed(chalk.green('Distillation complete. Intelligence stored.'));
  } catch (err) {
    spinner.fail(chalk.red('Distillation failed.'));
    console.error(err);
    process.exit(1);
  }

  // 2. Upgrade Core Mandates
  spinner.start('Upgrading core framework rules...');
  const ruleFiles = ['.clinerules', '.cursorrules', '.windsurfrules', 'CLAUDE.md'];
  ruleFiles.forEach(file => {
    if (fs.existsSync(file)) {
      let fileContent = fs.readFileSync(file, 'utf-8');
      if (!fileContent.includes('ironclad-distilled.md')) {
        fileContent += '\n---\n- **Distilled Intelligence**: Refer to \`.ai-core/rules/ironclad-distilled.md\` for consolidated elite mandates.';
        fs.writeFileSync(file, fileContent);
        spinner.text = `Updated ${file} with distilled intelligence link.`;
      }
    }
  });

  // Update timestamp in GEMINI.md
  if (fs.existsSync('GEMINI.md')) {
    const timestamp = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    let geminiContent = fs.readFileSync('GEMINI.md', 'utf-8');
    geminiContent = geminiContent.replace(/\*Last Updated:.*\*/, `*Last Updated: ${timestamp} (Phase 4 Evolution: Command Center Redesign)*`);
    fs.writeFileSync('GEMINI.md', geminiContent);
  }

  spinner.succeed(chalk.green('Core mandates upgraded to next tier.'));
  console.log(`\n${chalk.hex('#C2512B').bold('✨ Ironclad Evolution: SUCCESS. The framework has ascended.')}\n`);
}
