#!/bin/bash

# Ironclad Evolution & Upgrade Script
# Purpose: Distill intelligence from `.ai-core/skills/` into core mandates.

echo "🚀 Initiating Ironclad Evolution Engine..."

# 1. Distill Intelligence
echo "🧠 Distilling elite patterns from fetched repositories..."
DISTILL_FILE=".ai-core/rules/ironclad-distilled.md"
mkdir -p .ai-core/rules

cat << 'EOF' > "$DISTILL_FILE"
# 🧠 Ironclad Distilled Intelligence
*Auto-generated by the Ironclad Evolution Engine.*

## 1. Output Enforcement (from full-output-enforcement)
- **Mandate**: NEVER use placeholder comments (`// TODO`, `// implement here`, `...`).
- **Action**: Write the full, working implementation every single time.

## 2. Deep Architecture (from mattpocock/skills)
- **Mandate**: Surface architectural friction and propose deepening opportunities.
- **Action**: Prioritize locality and leverage. Use explicit composition over inheritance. Ensure the interface is the test surface.

## 3. Persistent Memory (from claude-mem & agentdb)
- **Mandate**: Maintain cross-session state via memory banks and Vector DBs.
- **Action**: Document architectural decisions in `ADRs` and synchronize business context with semantic search engines.

## 4. Swarm Orchestration (from ECC & compound-engineering)
- **Mandate**: Never work alone on complex, multi-file tasks.
- **Action**: Spawn parallel agent swarms: `feature-dev:code-architect` (design) -> `coder` (draft) -> `reviewer` (audit).

## 5. Visual Masterpiece (from ui-ux-pro-max & taste-skill)
- **Mandate**: Reject generic, AI-slop UI patterns.
- **Action**: Enforce premium visual design standards (bento grids, cinematic aesthetic, precise typography, micro-motion).

## 6. Systematic Methodology (from superpowers & Understand-Anything)
- **Mandate**: Methodology is Ironclad. Never skip to implementation.
- **Action**: Always follow the 5-step loop: Understand -> Plan -> Delegate -> Implement -> Verify.
EOF

echo "✅ Distillation complete. Intelligence stored in $DISTILL_FILE"

# 2. Upgrade Core Mandates
echo "⚙️ Upgrading core framework rules..."

# Use a temporary file to safely append/update rules
for rule_file in .clinerules .cursorrules .windsurfrules CLAUDE.md; do
  if [ -f "$rule_file" ]; then
    if ! grep -q "ironclad-distilled.md" "$rule_file"; then
      echo -e "\n---\n- **Distilled Intelligence**: Refer to \`.ai-core/rules/ironclad-distilled.md\` for consolidated elite mandates." >> "$rule_file"
      echo "✅ Updated $rule_file with distilled intelligence link."
    fi
  fi
done

# Update timestamp in GEMINI.md
TIMESTAMP=$(date +"%B %d, %Y")
if [ -f "GEMINI.md" ]; then
  sed -i.bak "s/\*Last Updated:.*\*/\*Last Updated: $TIMESTAMP (Phase 3 Evolution: God-Tier Distillation)\*/" GEMINI.md
  rm -f GEMINI.md.bak
  echo "✅ Updated GEMINI.md timestamp."
fi

echo "✅ Core mandates upgraded."
echo "✨ Ironclad Evolution: SUCCESS. The framework has ascended to the next tier."
