# Maintainer: Pasical <pasicalyang@gmail.com>
# This file is automatically generated
pkgname=everywhere-bin
pkgver=0.0.0
pkgrel=1
pkgdesc="Context-aware AI assistant for your desktop. Ready to respond intelligently, seamlessly integrating multiple LLMs and MCP tools."
arch=('x86_64')
url="https://github.com/Sylinko/Everywhere"
license=('BSL-1.1')
depends=('dotnet-runtime' 'fontconfig' 'libx11' 'libice' 'libsm' 'hicolor-icon-theme')
provides=('everywhere')
conflicts=('everywhere')

_filename="Everywhere-Linux-x64-v${pkgver}.tar.zst"
_iconfile="Everywhere-icon.png"

source=("${url}/releases/download/v${pkgver}/${_filename}"
        "https://raw.githubusercontent.com/Sylinko/Everywhere/main/LICENSE"
        "https://media.githubusercontent.com/media/Sylinko/Everywhere/refs/heads/main/img/Everywhere-icon.png")

sha256sums=('SKIP'
           'SKIP'
           'SKIP')

package() {
    cd "${srcdir}"
    mkdir -p "${pkgdir}/opt/Everywhere"
    bsdtar -xf "${_filename}" -C "${pkgdir}/opt/Everywhere"
    find "${pkgdir}" -type d -exec chmod 755 {} +
    mkdir -p "${pkgdir}/usr/bin"
    ln -s "/opt/Everywhere/Everywhere" "${pkgdir}/usr/bin/Everywhere"
    
    mkdir -p "${pkgdir}/usr/share/applications"
    cat > "${pkgdir}/usr/share/applications/Everywhere.desktop" << EOF
[Desktop Entry]
Name=Everywhere
Comment=A context-aware AI assistant for your desktop.
Exec=/usr/bin/Everywhere
X-KDE-StartupNotify=true
Icon=Everywhere
Type=Application
Terminal=false
Categories=Utility
Keywords=AI;tool;
EOF
    
    mkdir -p "${pkgdir}/usr/share/pixmaps"
    cp "${srcdir}/${_iconfile}" "${pkgdir}/usr/share/pixmaps/Everywhere.png"
    
    mkdir -p "${pkgdir}/usr/share/licenses/everywhere"
    if [ -f "${srcdir}/LICENSE" ]; then
        cp "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/everywhere/"
    fi
}